version: 0.0
os: linux
files:
  - source: /files/janus.cfg.sh
    destination: /usr/share/janus/scripts/
hooks:
  BeforeInstall:
    - location: scripts/install_janus.sh
      timeout: 300000
      runas: root
  AfterInstall:
    - location: scripts/set_permissions.sh
      timeout: 300
      runas: root
    - location: scripts/janus.transport.websockets.cfg.sh
      timeout: 300
      runas: janus
    - location: scripts/janus.transport.http.cfg.sh
      timeout: 300
      runas: janus
    - location: scripts/generate_certificate.sh
      timeout: 20000
      runas: janus
  ApplicationStart:
    - location: scripts/start_janus.sh
      timeout: 300
      runas: janus
  ApplicationStop:
    - location: scripts/stop_janus.sh
      timeout: 300
      runas: janus
  ValidateService:
    - location: scripts/validate_janus.sh
      timeout: 300
      runas: janus